### PR TITLE
Generate report when given an empty array

### LINKED ISSUE #46: Failed to generate report: TypeError upon report creation
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description
Running off of main, following the README instructions.

> Provide a clear and concise description of the issue, including what you expected to happen.
```
[...]
2025-11-03T05:55:31.517Z - info: Running validator Check Actions Runtime
2025-11-03T05:55:31.517Z - info: Running validator Check Actions Hard Coded Values
TypeError: Cannot read properties of undefined (reading 'concat')
    at /Users/myuser/gitrepos/auth0-checkmate/analyzer/lib/network_acl/checkNetworkACL.js:25:35
    at Array.forEach (<anonymous>)
    at /Users/myuser/gitrepos/auth0-checkmate/analyzer/lib/network_acl/checkNetworkACL.js:21:20
    at module.exports (/Users/myuser/gitrepos/auth0-checkmate/analyzer/lib/executeCheck.js:8:10)
    at checkNetworkACL (/Users/myuser/gitrepos/auth0-checkmate/analyzer/lib/network_acl/checkNetworkACL.js:7:10)
    at /Users/myuser/gitrepos/auth0-checkmate/analyzer/report.js:42:9
    at new Promise (<anonymous>)
    at /Users/myuser/gitrepos/auth0-checkmate/analyzer/report.js:33:14
    at Array.map (<anonymous>)
    at runProductionChecks (/Users/myuser/gitrepos/auth0-checkmate/analyzer/report.js:32:50)
2025-11-03T05:55:31.517Z - error: Error generating report: TypeError: Cannot read properties of undefined (reading 'concat')
failed to generate report
```

### Reproduction

Followed instructions on running from `main`.

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

### PR DESCRIPTION
**Pull request by mathewwoodyard-okta**
### Description

This PR resolves #46 by generating a report when given an empty array rather than throwing a `TypeError` and failing.

### References

#46 

### Testing

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

### CODE REVIEW

File: analyzer/lib/network_acl/checkNetworkACL.js [hunk 1]
```diff
@@ -15,14 +40,16 @@ function checkNetworkACL(options) {
...
         status: CONSTANTS.FAIL,
       });
     } else {
         networkAcl.forEach((acl) => {
         if (!acl.active) {
+          const description = acl.description || acl.name || acl.acl_id;
           report.push({
             field: "network_acl_inactive",
-            name: acl.description.concat(`(${acl.acl_id})`),
+            name: `${description}(${acl.acl_id})`,
```
Comment (hernanhht) [inline analyzer/lib/network_acl/checkNetworkACL.js]: if `description` equals the `acl.acl_id` value you have put in line 49, the name here will have the id twice, might be confusing.

File: tests/network_acl/checkNetworkACL.test.js [hunk 2]
```diff
@@ -0,0 +1,89 @@
+const { expect } = require("chai");
+const checkNetworkACL = require("../../analyzer/lib/network_acl/checkNetworkACL");
+const CONSTANTS = require("../../analyzer/lib/constants");
+
+describe("checkNetworkACL", function () {
```
Comment (hernanhht) [inline tests/network_acl/checkNetworkACL.test.js]: Based on how many `null/undefined` values you are trying to avoid, you might be missing more test cases for that

File: analyzer/lib/network_acl/checkNetworkACL.js [hunk 3]
```diff
@@ -15,14 +40,16 @@ function checkNetworkACL(options) {
     if (_.isEmpty(networkAcl)) {
       report.push({
         field: "no_network_acl",
+        name: "Tenant Access Control List",
         status: CONSTANTS.FAIL,
       });
     } else {
         networkAcl.forEach((acl) => {
         if (!acl.active) {
+          const description = acl.description || acl.name || acl.acl_id;
```
[the remark this answers is not in the document]
Comment (yangwang-okta) [reply analyzer/lib/network_acl/checkNetworkACL.js]: no it wont be.
